### ISSUE TITLE
目前还不支持原生Hbase客户端访问吗？

### ISSUE THREAD

**Issue by sladenew** [zhihu/zetta#8]
成功编译启动后会监听4个端口：
[2021/06/01 12:47:41.498 -04:00] [INFO] [server.go:93] ["server is running TCP listener"] [addr=0.0.0.0:4000]
[2021/06/01 12:47:41.498 -04:00] [INFO] [server.go:215] ["server is running MySQL protocol"] [addr=0.0.0.0:4001]
[2021/06/01 12:47:41.500 -04:00] [INFO] [http_status.go:123] ["for status and metrics report"] ["listening on addr"=0.0.0.0:10090]
[2021/06/01 12:47:41.501 -04:00] [INFO] [thrift_server.go:88] ["hbase thrift server start"] [addr=0.0.0.0:9090]
这四个监听端口，都不是zk的协议，如果使用thrift接入的话，客户端改造成本会比较高。

**Comment by pseudocodes** [comment]
> 成功编译启动后会监听4个端口：
> [2021/06/01 12:47:41.498 -04:00] [INFO] [server.go:93] ["server is running TCP listener"] [addr=0.0.0.0:4000]
> [2021/06/01 12:47:41.498 -04:00] [INFO] [server.go:215] ["server is running MySQL protocol"] [addr=0.0.0.0:4001]
> [2021/06/01 12:47:41.500 -04:00] [INFO] [http_status.go:123] ["for status and metrics report"] ["listening on addr"=0.0.0.0:10090]
> [2021/06/01 12:47:41.501 -04:00] [INFO] [thrift_server.go:88] ["hbase thrift server start"] [addr=0.0.0.0:9090]
> 这四个监听端口，都不是zk的协议，如果使用thrift接入的话，客户端改造成本会比较高。

目前内部已经可以支持 HBase 原生的 Get, Mutate, Scan, Multi 数据访问接入，待完备会开放出来

**Comment by sladenew** [comment]
> > 成功编译启动后会监听4个端口：
> > [2021/06/01 12:47:41.498 -04:00] [INFO] [server.go:93] ["server is running TCP listener"] [addr=0.0.0.0:4000]
> > [2021/06/01 12:47:41.498 -04:00] [INFO] [server.go:215] ["server is running MySQL protocol"] [addr=0.0.0.0:4001]
> > [2021/06/01 12:47:41.500 -04:00] [INFO] [http_status.go:123] ["for status and metrics report"] ["listening on addr"=0.0.0.0:10090]
> > [2021/06/01 12:47:41.501 -04:00] [INFO] [thrift_server.go:88] ["hbase thrift server start"] [addr=0.0.0.0:9090]
> > 这四个监听端口，都不是zk的协议，如果使用thrift接入的话，客户端改造成本会比较高。
> 
> 目前内部已经可以支持 HBase 原生的 Get, Mutate, Scan, Multi 数据访问接入，待完备会开放出来
